FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# this is not required (but nor is it harmful) when using docker-compose
# it has been left in to remind us that in a non-docker-compose world we
# still need it
COPY . .

CMD ["npm", "run", "start"]
